// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/yuru-sha/go-cli-ddd/internal/application/usecase"
	"github.com/yuru-sha/go-cli-ddd/internal/infrastructure/api/externalapi1"
	"github.com/yuru-sha/go-cli-ddd/internal/infrastructure/config"
	"github.com/yuru-sha/go-cli-ddd/internal/infrastructure/http"
	"github.com/yuru-sha/go-cli-ddd/internal/infrastructure/notification"
	"github.com/yuru-sha/go-cli-ddd/internal/infrastructure/persistence/mysql"
	"github.com/yuru-sha/go-cli-ddd/internal/infrastructure/secrets"
	"github.com/yuru-sha/go-cli-ddd/internal/interfaces/cli"
	"gorm.io/gorm"
)

// InitializeApp はアプリケーションを初期化します。
func InitializeApp(params AppParams) (*cli.RootCommand, error) {
	options := ProvideConfigOptions(params)
	configConfig, err := config.LoadConfig(options)
	if err != nil {
		return nil, err
	}
	database, err := mysql.NewDatabase(configConfig)
	if err != nil {
		return nil, err
	}
	db := ProvideDatabaseConnection(database)
	mySQLAccountRepository := mysql.NewAccountRepository(db)
	httpConfig := ProvideHTTPConfig(configConfig)
	client := http.NewHTTPClient(httpConfig)
	manager, err := secrets.NewManager(configConfig)
	if err != nil {
		return nil, err
	}
	externalAPI1AccountRepository := externalapi1.NewAccountRepository(configConfig, client, manager)
	notificationRepository := notification.NewRepository(configConfig)
	accountUseCase := usecase.NewAccountUseCase(mySQLAccountRepository, externalAPI1AccountRepository, notificationRepository)
	accountHandler := cli.NewAccountHandler(accountUseCase)
	accountCommand := cli.NewAccountCommand(accountHandler)
	mySQLCampaignRepository := mysql.NewCampaignRepository(db)
	externalAPI1CampaignRepository := externalapi1.NewCampaignRepository(configConfig, client, manager)
	campaignUseCase := usecase.NewCampaignUseCase(mySQLCampaignRepository, externalAPI1CampaignRepository, mySQLAccountRepository)
	campaignHandler := cli.NewCampaignHandler(campaignUseCase)
	campaignCommand := cli.NewCampaignCommand(campaignHandler)
	masterUseCase := usecase.NewMasterUseCase(accountUseCase, campaignUseCase)
	masterHandler := cli.NewMasterHandler(masterUseCase)
	masterCommand := cli.NewMasterCommand(masterHandler)
	commandModules := ProvideCommandModules(accountCommand, campaignCommand, masterCommand)
	command, err := ProvideRootCommand(commandModules)
	if err != nil {
		return nil, err
	}
	return command, nil
}

type AppParams struct {
	ConfigPath string
	Env        string
}

func ProvideConfigOptions(params AppParams) *config.Options {
	return config.NewConfigOptions(params.ConfigPath, params.Env)
}

func ProvideDatabaseConfig(cfg *config.Config) *config.DatabaseConfig {
	return &cfg.Database
}

func ProvideHTTPConfig(cfg *config.Config) *config.HTTPConfig {
	return &cfg.HTTP
}

func ProvideAWSConfig(cfg *config.Config) *config.AWSConfig {
	return &cfg.AWS
}

func ProvideDatabaseConnection(db *mysql.Database) *gorm.DB {
	return db.DB
}

func ProvideCommandModules(
	accountCmd *cli.AccountCommand,
	campaignCmd *cli.CampaignCommand,
	masterCmd *cli.MasterCommand,
) []cli.CommandModule {
	return []cli.CommandModule{accountCmd, campaignCmd, masterCmd}
}

func ProvideRootCommand(modules []cli.CommandModule) (*cli.RootCommand, error) {
	rootCmd := cli.NewRootCommand()
	for _, module := range modules {
		rootCmd.Register(module)
	}
	return rootCmd, nil
}
